# Generated by Django 4.1.6 on 2023-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwd',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='per100',
        ),
        migrations.AddField(
            model_name='rules',
            name='LHS',
            field=models.CharField(default='S', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='RHS',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='prob',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
