# Generated by Django 4.1.6 on 2023-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_passwd_remove_rules_per100_rules_lhs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='LHS',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='rules',
            name='RHS',
            field=models.CharField(default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='rules',
            name='prob',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
