# Generated by Django 4.1.6 on 2023-03-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_rules_lhs_alter_rules_rhs_alter_rules_prob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
