# Generated by Django 4.1.6 on 2023-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_rules_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='totalPret',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rule',
            name='totalTer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='LHS',
            field=models.CharField(default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='rule',
            name='RHS',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
