# Generated by Django 4.1.6 on 2023-05-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rule_totalpret_rule_totalter_alter_rule_lhs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='modelo',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
