# Generated by Django 4.1.6 on 2023-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rule_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='null', max_length=100)),
                ('numPasswords', models.IntegerField(default=0)),
                ('numRules', models.IntegerField(default=0)),
            ],
        ),
    ]
