# Generated by Django 4.1.6 on 2023-07-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_trainmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='prob',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
